trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  fetchDepth: 0

- script: |
    echo "Build Branch: $(Build.SourceBranch)"
    echo "Branch Name: $(Build.SourceBranchName)"
  displayName: 'Check Branch'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: 'Setup Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pytest-cov
  displayName: 'Install Dependencies'

- script: |
    pytest --cov=. --cov-report=xml
  displayName: 'Run Tests and Generate Coverage'

- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonar-connection'
    scannerMode: 'cli'
    configMode: 'file'
  displayName: 'Prepare SonarQube Analysis'

- script: |
    echo "Checking Sonar variables..."
    env | grep -i SONAR || true
  displayName: 'Check SonarQube Variables'

- task: SonarQubeAnalyze@8
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
  displayName: 'Run SonarQube Analysis'

- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate'
