trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  fetchDepth: 0

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: 'Setup Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

# SonarQube Prepare
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonarqube-connection'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'python-code-analysis'
    cliProjectName: 'Python Code Analysis'
    cliSources: '.'
  displayName: 'Prepare SonarQube Analysis'

- script: |
    pytest --cov=. --cov-report=xml
  displayName: 'Run Tests'

# SonarQube Analysis
- task: SonarQubeAnalyze@8
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
  displayName: 'Run SonarQube Analysis'

# Quality Gate
- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate'